### ISSUE TITLE
HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by ScoutMentality** [TBGAnsell/LipIDens#5]
Hi,

Does a URL in the main LipIDens run script need to be updated?  I keep getting the following error:

Traceback (most recent call last):
  File "/home/dan/LipIDens/lipidens_master_run.py", line 91, in <module>
    ps.fetch_CG_itp(forcefield, path)
  File "/xtal1/dan/LipIDens/lipidens/simulation/simulation.py", line 71, in fetch_CG_itp
    urllib.request.urlretrieve("http://cgmartini.nl/images/parameters/ITP/{}.itp".format(forcefield), "{}/itp_files/{}.itp".format(path, forcefield))
  File "/home/dan/miniconda3/envs/LipIDens/lib/python3.9/urllib/request.py", line 239, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/dan/miniconda3/envs/LipIDens/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/home/dan/miniconda3/envs/LipIDens/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/home/dan/miniconda3/envs/LipIDens/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/home/dan/miniconda3/envs/LipIDens/lib/python3.9/urllib/request.py", line 555, in error
    result = self._call_chain(*args)
  File "/home/dan/miniconda3/envs/LipIDens/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/home/dan/miniconda3/envs/LipIDens/lib/python3.9/urllib/request.py", line 747, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/home/dan/miniconda3/envs/LipIDens/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/home/dan/miniconda3/envs/LipIDens/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/home/dan/miniconda3/envs/LipIDens/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/home/dan/miniconda3/envs/LipIDens/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/home/dan/miniconda3/envs/LipIDens/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

Thank you!
Dan

**Comment by TBGAnsell** [comment]
Hi Dan, thanks for bringing this to my attention and for your patience. I've fixed the issues with the https addresses.
